http:
  host : "0.0.0.0"
  port : "8081"
  path: "/api/*"
  readTimeout : "30000"
  
sf:
  userName : "tihitinadereje@gmail.com"
  password : "0909704209Gt#1"
  securityToken: "pBDRkPCKk5Yqnxh2KZ11Zflc"
  authorizationURL : "https://login.salesforce.com/services/Soap/u/60.0"
  
field:
  contract: "LastModifiedDate, ContractNumber, AccountId,ContractTerm, CustomerSignedDate, StatusCode, StartDate,EndDate, Status, CreatedDate,Id "